config/routes.rb
Backbone::Application.routes.draw do
  devise_for :users

  root 'home#index'
  get "auth/:provider/callback" => "omniauths#create"
  resources :settings do
    member do
      put :approve
    end
  end
  resources :venues

  

end

app/models/location.rb
class Location
  include Mongoid::Document
  field :location,:type => string
  field :tag ,:type => string
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable,:confirmable, :validatable
  has_many :venues,:dependent => :destroy
  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable
   
  ## extra field
  field :first_name, :type => String
  field :last_name, :type => String
  field :username, :type => String
  field :uid, :type => String
  field :provider, :type => String
  field :status,:type => Boolean,:default => false
  field :role,:type => String,:default => "user"
  
  validates :first_name,:last_name,:username,:presence => true

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
  
  def self.create_from_omniauth(auth)
    user = User.where(:uid => auth["uid"]).first
    if user == nil
      user = User.new(:first_name => auth["extra"]["raw_info"]["first_name"],:last_name => auth["extra"]["raw_info"]["last_name"],:username => auth["extra"]["raw_info"]["username"])
      user.email = auth["extra"]["raw_info"]["email"]
      user.uid = auth["uid"]
      user.provider = auth["provider"]
      #      user.confirmed_at = Time.now
      #      user.confirmation_token = nil
      user.save(:validate => false)
      user.confirm!
    end
    return user
  end
end

app/models/venue.rb
class Venue
  include Mongoid::Document
  belongs_to :user
  field :user_id
  field :name,:type => String
  field :description,:type => String
  field :location,:type => String
  field :location_type,:type => String
  field :latitude,:type => String
  field :longitude,:type => String
  validates :name,:location,:presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, :if => :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    root_path
  end
  
  def is_login
    unless current_user
      flash[:error] = "Please login!"
      redirect_to root_path
    end
  end
  
  def is_admin
    unless current_user and current_user.role == "admin"
      flash[:error] = "Access denied!"
      redirect_to root_path
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { 
      |u| u.permit([:username,:first_name,:last_name,:email,:password,:password_confirmation]) 
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/omniauths_controller.rb
class OmniauthsController < ApplicationController
  
  def create
    auth = request.env['omniauth.auth']
    user = User.create_from_omniauth(auth)
    if user
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect user, :event => :authentication
    else
      flash[:notice] = "Login failed."
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Updation succeed!"
      redirect_to root_path
    else
      flash[:error] = "Updation failed!"
      render :action => :edit
    end
  end
  
  def approve
    @user = User.find(params[:id])
    @user.status = params[:status]
    @user.save(:validate => false)
    @status = @user.status == true ? "Approved" : "Not Approved"
    render
  end
  
  private
  def user_params
    params.require(:user).permit!
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :is_login
  def index
    @venues = current_user.venues.where(:role => "user")
  end
  
  def new
    @venue = Venue.new
  end
  
  def create
    @venue = current_user.venues.new(venue_params)
    if @venue.save
      flash[:notice] = "Venue uploaded successfully!"
      redirect_to venues_path
    else
      flash[:error] = "Venue upload failed!"
      render :action => :new
    end
  end
  
  private
  def venue_params
    params.require(:venue).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauths_helper.rb
module OmniauthsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/home/index.html.erb
Welcome

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Backbone" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body  style="padding: 60px;">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Backbone</a>
          <div class="container nav-collapse">
            <ul class="nav" style="float:right;">
              <% if current_user %>
                <% if current_user.role == "admin" %>
                  <li><%= link_to "Users",settings_path %></li>
                <% else %>
                  <li><%= link_to "Settings", edit_setting_path(current_user)  %></li>
                  <li><%= link_to "Upload Venue", new_venue_path  %></li>
                <% end %>
                <li><%= link_to "Logout", destroy_user_session_path,:method => :delete  %></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path  %></li>
                <li><%= link_to "Sign Up", new_user_registration_path  %></li>
                <li><%= link_to "Login With Facebook", "/auth/facebook"  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/settings/approve.js.erb
$("#approve").html('<%= @status %>');
$("#approve_link").html('<a rel="nofollow" href="/settings/2/approve?status=<%= @status == "Approved" ? false : true %>" data-remote="true" data-method="put"><%= @status == "Approved" ? "Not Approve" : "Approve" %></a>')

app/views/settings/edit.html.erb
<%= form_for @user, :url => setting_path(@user) do |f| %>
  <%= f.error_messages %>

  <div><%= f.label :username %><br />
    <%= f.text_field :username, :autofocus => true %></div>

  <div><%= f.label :first_name %><br />
    <%= f.text_field :first_name %></div>

  <div><%= f.label :last_name %><br />
    <%= f.text_field :last_name %></div>

  <div><%= f.submit "Update" %></div>
<% end %>

app/views/settings/index.html.erb
<table class="table">
  <tr>
    <th>User Name</th>
    <th>Last Name</th>
    <th>First Name</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td id="approve"><%= user.status == true ? "Approved" : "Not Approved" %></td>
      <td id="approve_link"><%= user.status == true ? (link_to "Not Approve",approve_setting_path(user,:status => false),:method => :put,:remote => true) : (link_to "Approve",approve_setting_path(user,:status => true),:method => :put,:remote => true) %></td>
    </tr>
  <% end %>
</table>

app/views/venues/index.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Location</th>
    <th></th>
  </tr>
  <% @venues.each do |venue| %>
    <tr>
      <td><%= venue.name %></td>
      <td><%= venue.description %></td>
      <td><%= venue.location %></td>
    </tr>
  <% end %>
</table>

app/views/venues/new.html.erb
<h2>Upload Venue</h2>

<%= form_for @venue do |f| %>
  <%= f.error_messages %>

  <div><%= f.label :name %><br />
    <%= f.text_field :name, :autofocus => true %></div>

  <div><%= f.label :description %><br />
    <%= f.text_field :description %></div>

  <div><%= f.label :location %><br />
    <%= f.text_field :location %>&nbsp;Tag: &nbsp;<%= f.select :location_type,%w(city state country) %></div>

  <div><%= f.submit "Create" %></div>
<% end %>